# policy constants

POLICY_USE_FOREVER = "Use Forever"
POLICY_USE_UNTIL = "Use Until"
POLICY_USE_ONCE_BEFORE = "Use Once Before"

POLICY_IDS = {
    POLICY_USE_FOREVER: 1,
    POLICY_USE_UNTIL: 2,
    POLICY_USE_ONCE_BEFORE: 3,
}

# api key constants

STATUS_ACTIVE = "ACTIVE"
STATUS_INACTIVE = "INACTIVE"
